name: Insider Gaming Tricks Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run a test command
        run: echo "Workflow InsiderGamingtriks running!"
