name: Auto News

on:
  schedule:
    - cron: "0 9 * * *"
    - cron: "0 18 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test NewsAPI
        run: curl https://newsapi.org/v2/everything?q=counter-strike&apiKey=${{ secrets.NEWS_API_KEY }}
